
[General]
	#Use whitelist only
	whitelist = false
	#Insert into players inventory when possible instead of spewing all the items on the ground
	inventoryInsert = true
	#Stack size of dropped loot will be a random number between 0 and maxStackSize
	#Range: 0 ~ 64
	maxStackSize = 1
	#Number of dropped stacks per bundle will be between minLootAmount and maxLootAmount
	#Range: > 0
	minLootAmount = 3
	#Number of dropped stacks per bundle will be between minLootAmount and maxLootAmount
	#Range: > 0
	maxLootAmount = 3
	#List of strings that an item name must not contain in order for it to be considered a valid loot item. Item name can be partial and can contain the mod id as well to disallow an entire mods items.
	disallowedItemNames = ["creative", "spawn_egg", "admin", "autosmithingtable", "additionallanterns", "additional_lights", "botanypots", "book", "bedrock", "biomesoplenty", "bambooeverything", "chipped", "chest", "cookingforblockheads", "cobblemon", "cheat", "cheats", "chiselsandbits", "crafting_on_a_stick", "chimes", "debug", "dust", "decorative_blocks", "dev", "dramaticdoors", "doggytalents", "developer", "engineersdecor", "fake", "framedblocks", "framedcompactdrawers", "guide", "hopper", "indev", "ingot", "jumbofurnace", "kubejs", "lootr", "minecraft:enchanted_book", "manual", "mcwdoors", "mcwbridges", "mcwroofs", "mcwwindows", "macawsbridgesbop", "mcwfences", "mcwfurnitures", "mcwpaths", "mcwfencesbop", "mcwfurnitures", "mcwfencesbop", "macawsroofsbop", "mcwlights", "nuke", "nugget", "ore", "patchouli", "plonk", "prefab", "pitg", "player_head", "puzzle", "quark", "rubber", "relics:delay_ring", "relics:space_dissector", "relics:slime_heart", "rechiseled", "storagedrawers", "sophisticatedstorage", "tombstone", "testing", "tombstone:book_of_disenchantment", "tombstone:book_of_recycling", "tombstone:book_of_repairing", "tombstone:book_of_magic_impregnation", "wip", "workbench", "viescraftmachines"]

